In [2]:
### Get the ingredients for each recipe

In [1]:
import pandas as pd

pd.set_option('display.max_columns', 23)
df_all_food_com = pd.read_csv('csv_files/food_com_db_w_units.csv') ## dataset with a register of food recipes 

# Create a new dataframe associating each recipe to a group of ingredients with his measures, units and servings
# Servings - For how many people is the recipe
df_recipes_with_ings = df_all_food_com.groupby('title').agg({'ingredient': lambda x: list(x), 'measure': lambda x: list(x), 
                                                             'unit': lambda x: list(x), 'servings': lambda x: list(x)}).reset_index()
df_recipes_with_ings.columns = ['title', 'ingredients', 'measures', 'units', 'servings']

In [2]:
df_recipes_with_ings

,title,ingredients,measures,units,servings
0,4 Hour Beef stew,"[stew meat, onion, carrots, celery, potatoes, ...","[907.18-1360.77, 1, 4, 2, 3, 4.92, 4.92, 14.78...","[g, large, nan, stalk, nan, ml, ml, ml, ml, ml]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
1,Add Anything French Rolls or Baguettes,"[warm water, active dry yeast, sugar, salt, al...","[946.36, 29.57, 59.16, 19.71, 2365.9, 2, 29.58...","[ml, ml, ml, ml, ml, nan, ml, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]"
2,Add in Anything Muffins!,"[flour, sugar, sugar, baking powder, baking so...","[354.88, 118.29, 29.58, 7.39, 1.23, 1.23, 118....","[ml, ml, ml, ml, ml, ml, ml, ml, large, ml]","[12, 12, 12, 12, 12, 12, 12, 12, 12, 12]"
3,Ali's Chicken Goat Cheese; Pesto; Basil; Su...,"[chicken breasts, goat cheese, fresh basil lea...","[10-12, 226.79, 118.29-177.44, 118.29-236.59, ...","[nan, g, ml, ml, g, ml, ml, ml, ml, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
4,All In Meatless Mincemeat,"[apples, carrots, beet, tomatoes, orange, lemo...","[3, 354.88, 1, 510.29, 1, 1, 236.59, 177.44, 4...","[large, ml, medium, g, nan, nan, ml, ml, ml, m...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
...,...,...,...,...,...
418593,zippy Italian Dressing,"[olive oil, white wine vinegar, salt, sugar, d...","[236.59, 78.07, 2.46, 7.39, 1.23, 1.23, 1.23, ...","[ml, ml, ml, ml, ml, ml, ml, ml, ml, ml, ml, m...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
418594,zucchini herb bread,"[water, honey, oil, zucchini, whole wheat flou...","[177.44, 14.79, 22.18, 236.59, 236.59, 591.47,...","[ml, ml, ml, ml, ml, ml, ml, ml, ml, ml]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
418595,{ Cookies by Design } Cookies on a Stick,"[butter, Eagle Brand Condensed Milk, light bro...","[113.39, 396.89, 118.29, 118.29, 1, 4.92, 4.92...","[g, g can, ml packed, ml, nan, ml, ml, ml, ml,...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
418596,{ Cookies by Design } Sugar Shortbread Cookies,"[granulated sugar, shortening, eggs, flour, cr...","[236.59, 236.59, 3, 709.77, 9.85, 9.85, 4.92]","[ml, ml, nan, ml, ml, ml, ml]","[nan, nan, nan, nan, nan, nan, nan]"
418597,{Beijinhos De Coco} Brazilian Coconut Treats,"[condensed milk, coconut flakes, butter, cloves]","[397, 100, 14.79, 16]","[g can, g, ml, nan]","[nan, nan, nan, nan]"

In [3]:
# Convert all the title letters to lower case 
df_recipes_with_ings['title'] = df_recipes_with_ings['title'].str.lower()

In [4]:
df_recipes_with_ings

,title,ingredients,measures,units,servings
0,4 hour beef stew,"[stew meat, onion, carrots, celery, potatoes, ...","[907.18-1360.77, 1, 4, 2, 3, 4.92, 4.92, 14.78...","[g, large, nan, stalk, nan, ml, ml, ml, ml, ml]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
1,add anything french rolls or baguettes,"[warm water, active dry yeast, sugar, salt, al...","[946.36, 29.57, 59.16, 19.71, 2365.9, 2, 29.58...","[ml, ml, ml, ml, ml, nan, ml, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]"
2,add in anything muffins!,"[flour, sugar, sugar, baking powder, baking so...","[354.88, 118.29, 29.58, 7.39, 1.23, 1.23, 118....","[ml, ml, ml, ml, ml, ml, ml, ml, large, ml]","[12, 12, 12, 12, 12, 12, 12, 12, 12, 12]"
3,ali's chicken goat cheese; pesto; basil; su...,"[chicken breasts, goat cheese, fresh basil lea...","[10-12, 226.79, 118.29-177.44, 118.29-236.59, ...","[nan, g, ml, ml, g, ml, ml, ml, ml, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
4,all in meatless mincemeat,"[apples, carrots, beet, tomatoes, orange, lemo...","[3, 354.88, 1, 510.29, 1, 1, 236.59, 177.44, 4...","[large, ml, medium, g, nan, nan, ml, ml, ml, m...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
...,...,...,...,...,...
418593,zippy italian dressing,"[olive oil, white wine vinegar, salt, sugar, d...","[236.59, 78.07, 2.46, 7.39, 1.23, 1.23, 1.23, ...","[ml, ml, ml, ml, ml, ml, ml, ml, ml, ml, ml, m...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
418594,zucchini herb bread,"[water, honey, oil, zucchini, whole wheat flou...","[177.44, 14.79, 22.18, 236.59, 236.59, 591.47,...","[ml, ml, ml, ml, ml, ml, ml, ml, ml, ml]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
418595,{ cookies by design } cookies on a stick,"[butter, Eagle Brand Condensed Milk, light bro...","[113.39, 396.89, 118.29, 118.29, 1, 4.92, 4.92...","[g, g can, ml packed, ml, nan, ml, ml, ml, ml,...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
418596,{ cookies by design } sugar shortbread cookies,"[granulated sugar, shortening, eggs, flour, cr...","[236.59, 236.59, 3, 709.77, 9.85, 9.85, 4.92]","[ml, ml, nan, ml, ml, ml, ml]","[nan, nan, nan, nan, nan, nan, nan]"
418597,{beijinhos de coco} brazilian coconut treats,"[condensed milk, coconut flakes, butter, cloves]","[397, 100, 14.79, 16]","[g can, g, ml, nan]","[nan, nan, nan, nan]"

In [5]:
# Check if there is duplicate recipes
duplicate_titles = df_recipes_with_ings[df_recipes_with_ings.duplicated(subset=['title'], keep=False)]
#duplicate_titles

In [6]:
# Remove all the duplicate recipes
df_recipes_with_ings = df_recipes_with_ings.drop_duplicates(subset=['title'])

In [7]:
df_recipes_with_ings

,title,ingredients,measures,units,servings
0,4 hour beef stew,"[stew meat, onion, carrots, celery, potatoes, ...","[907.18-1360.77, 1, 4, 2, 3, 4.92, 4.92, 14.78...","[g, large, nan, stalk, nan, ml, ml, ml, ml, ml]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
1,add anything french rolls or baguettes,"[warm water, active dry yeast, sugar, salt, al...","[946.36, 29.57, 59.16, 19.71, 2365.9, 2, 29.58...","[ml, ml, ml, ml, ml, nan, ml, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]"
2,add in anything muffins!,"[flour, sugar, sugar, baking powder, baking so...","[354.88, 118.29, 29.58, 7.39, 1.23, 1.23, 118....","[ml, ml, ml, ml, ml, ml, ml, ml, large, ml]","[12, 12, 12, 12, 12, 12, 12, 12, 12, 12]"
3,ali's chicken goat cheese; pesto; basil; su...,"[chicken breasts, goat cheese, fresh basil lea...","[10-12, 226.79, 118.29-177.44, 118.29-236.59, ...","[nan, g, ml, ml, g, ml, ml, ml, ml, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
4,all in meatless mincemeat,"[apples, carrots, beet, tomatoes, orange, lemo...","[3, 354.88, 1, 510.29, 1, 1, 236.59, 177.44, 4...","[large, ml, medium, g, nan, nan, ml, ml, ml, m...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
...,...,...,...,...,...
418593,zippy italian dressing,"[olive oil, white wine vinegar, salt, sugar, d...","[236.59, 78.07, 2.46, 7.39, 1.23, 1.23, 1.23, ...","[ml, ml, ml, ml, ml, ml, ml, ml, ml, ml, ml, m...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
418594,zucchini herb bread,"[water, honey, oil, zucchini, whole wheat flou...","[177.44, 14.79, 22.18, 236.59, 236.59, 591.47,...","[ml, ml, ml, ml, ml, ml, ml, ml, ml, ml]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
418595,{ cookies by design } cookies on a stick,"[butter, Eagle Brand Condensed Milk, light bro...","[113.39, 396.89, 118.29, 118.29, 1, 4.92, 4.92...","[g, g can, ml packed, ml, nan, ml, ml, ml, ml,...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
418596,{ cookies by design } sugar shortbread cookies,"[granulated sugar, shortening, eggs, flour, cr...","[236.59, 236.59, 3, 709.77, 9.85, 9.85, 4.92]","[ml, ml, nan, ml, ml, ml, ml]","[nan, nan, nan, nan, nan, nan, nan]"
418597,{beijinhos de coco} brazilian coconut treats,"[condensed milk, coconut flakes, butter, cloves]","[397, 100, 14.79, 16]","[g can, g, ml, nan]","[nan, nan, nan, nan]"

In [8]:
# Search through the exact word 
search_name = 'gobi manchurian'
found_recipes = df_recipes_with_ings[df_recipes_with_ings['title']==search_name]

In [9]:
found_recipes

,title,ingredients,measures,units,servings
167219,gobi manchurian,"[cauliflower, spring onion, gingerroot, garlic...","[1, 1, 9.85, 4.92, 44.37, 59.14, 1.23, 2, 44.3...","[medium, bunch, ml, ml, ml, ml, ml, nan, ml, m...","[3-5, 3-5, 3-5, 3-5, 3-5, 3-5, 3-5, 3-5, 3-5, ..."

In [10]:
# Search through the exact word with isin function
search_names = ['gobi manchurian']
found_recipes = df_recipes_with_ings[df_recipes_with_ings['title'].isin(search_names)]

In [11]:
found_recipes

,title,ingredients,measures,units,servings
167219,gobi manchurian,"[cauliflower, spring onion, gingerroot, garlic...","[1, 1, 9.85, 4.92, 44.37, 59.14, 1.23, 2, 44.3...","[medium, bunch, ml, ml, ml, ml, ml, nan, ml, m...","[3-5, 3-5, 3-5, 3-5, 3-5, 3-5, 3-5, 3-5, 3-5, ..."

In [17]:
search_names = ['sarson da saag']
# Filtering out the rows containing the found recipes
found_recipes = df_recipes_with_ings[df_recipes_with_ings['title'].str.contains('|'.join(search_names))]

In [18]:
found_recipes

Empty DataFrame
Columns: [title, ingredients, measures, units, servings]
Index: []

In [14]:
# Dropping the found recipes from df_recipes_with_ings
df_recipes_with_ings = df_recipes_with_ings.drop(found_recipes.index)

In [15]:
df_recipes_with_ings

,title,ingredients,measures,units,servings
0,4 hour beef stew,"[stew meat, onion, carrots, celery, potatoes, ...","[907.18-1360.77, 1, 4, 2, 3, 4.92, 4.92, 14.78...","[g, large, nan, stalk, nan, ml, ml, ml, ml, ml]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
1,add anything french rolls or baguettes,"[warm water, active dry yeast, sugar, salt, al...","[946.36, 29.57, 59.16, 19.71, 2365.9, 2, 29.58...","[ml, ml, ml, ml, ml, nan, ml, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]"
2,add in anything muffins!,"[flour, sugar, sugar, baking powder, baking so...","[354.88, 118.29, 29.58, 7.39, 1.23, 1.23, 118....","[ml, ml, ml, ml, ml, ml, ml, ml, large, ml]","[12, 12, 12, 12, 12, 12, 12, 12, 12, 12]"
3,ali's chicken goat cheese; pesto; basil; su...,"[chicken breasts, goat cheese, fresh basil lea...","[10-12, 226.79, 118.29-177.44, 118.29-236.59, ...","[nan, g, ml, ml, g, ml, ml, ml, ml, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
4,all in meatless mincemeat,"[apples, carrots, beet, tomatoes, orange, lemo...","[3, 354.88, 1, 510.29, 1, 1, 236.59, 177.44, 4...","[large, ml, medium, g, nan, nan, ml, ml, ml, m...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
...,...,...,...,...,...
418593,zippy italian dressing,"[olive oil, white wine vinegar, salt, sugar, d...","[236.59, 78.07, 2.46, 7.39, 1.23, 1.23, 1.23, ...","[ml, ml, ml, ml, ml, ml, ml, ml, ml, ml, ml, m...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
418594,zucchini herb bread,"[water, honey, oil, zucchini, whole wheat flou...","[177.44, 14.79, 22.18, 236.59, 236.59, 591.47,...","[ml, ml, ml, ml, ml, ml, ml, ml, ml, ml]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
418595,{ cookies by design } cookies on a stick,"[butter, Eagle Brand Condensed Milk, light bro...","[113.39, 396.89, 118.29, 118.29, 1, 4.92, 4.92...","[g, g can, ml packed, ml, nan, ml, ml, ml, ml,...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
418596,{ cookies by design } sugar shortbread cookies,"[granulated sugar, shortening, eggs, flour, cr...","[236.59, 236.59, 3, 709.77, 9.85, 9.85, 4.92]","[ml, ml, nan, ml, ml, ml, ml]","[nan, nan, nan, nan, nan, nan, nan]"
418597,{beijinhos de coco} brazilian coconut treats,"[condensed milk, coconut flakes, butter, cloves]","[397, 100, 14.79, 16]","[g can, g, ml, nan]","[nan, nan, nan, nan]"

In [16]:
# Check if all rice recipes were deleted
df_without_rice = df_recipes_with_ings[df_recipes_with_ings['title'].str.contains('sarson da saag')]
df_without_rice

Empty DataFrame
Columns: [title, ingredients, measures, units, servings]
Index: []